### ISSUE TITLE
servisten yanlış değerler geliyor.

### ISSUE THREAD

**Issue by i5kender** [prosman/doviz-borsa-kripto-api#2]
Merhaba,

https://api.canlidoviz.com/web/items?marketId=1&type=0
"name":"Amerikan Doları",
"code":"USD",
"todayLowestBuyPrice":5.3059000968933105,
"todayHighestBuyPrice":5.5282001495361328,
"todayLowestSellPrice":5.310999870300293,
"todayHighestSellPrice":5.5314998626708984,
"yesterdayClosingBuyPrice":5.4556999206542969,
"yesterdayClosingSellPrice":5.4566998481750488,
"buyPrice":5.3440999984741211,
"sellPrice":5.3494000434875488,
"dailyChange":-0.11159992218017578,
"dailyChangePercentage":-0.02045565625002185,
"lastUpdateDate":"19-11-2018 09:47:58"

servisten gelen data yukarıdaki gibidir fakat canlidoviz.com sitesinde aynı zamanda
% 0.2999 5.3436 5.3503 şeklindedir. Birinde dolar günlük olarak yükselişte birinde düşüşte gözükmektedir. Bu arada doviz.com apileri v1 ve v5 ikiside çalışmamaktadır. Bunlarda olan değişiklikleri de ekleyebilirmisiniz ?

**Comment by oguzhanahiskali** [comment]
tarihe dipnot: 30.03.2019 aynı vakka yaşanmaktadır.

**Comment by kcankaynak** [comment]
Halen yanlış geliyor, bu API bildiğin bozuk :)

**Comment by prosman** [comment]
Güncellendi
