### ISSUE TITLE
bu servisler suan hata veriyor

### ISSUE THREAD

**Issue by rozeridilar** [prosman/doviz-borsa-kripto-api#3]
Merhabalar,
https://api.canlidoviz.com/web/items?marketId=1&type=0 bu servisten degerler donmuyor suan

**Comment by iskndrcnr** [comment]
> Merhabalar,
> https://api.canlidoviz.com/web/items?marketId=1&type=0 bu servisten degerler donmuyor suan

https://napi.canlidoviz.com/items/current?marketId=0&code=USD

**Comment by prosman** [comment]
Güncellendi
